# .trufflehog.yaml - Security Exclusion Configuration
# Documentation: https://github.com/trufflesecurity/trufflehog

# 1. Excluded Paths: Files that should NEVER be scanned.
# Ideal for test files with synthetic data or documentation.

exclude_paths:
    # Documentación y Guías (donde solemos poner ejemplos de tokens)
    - "README.md"
    - "SECURITY.md"
    - "CONTRIBUTING.md"
    - "docs/.*"

    # Archivos de configuración de entorno y editores
    - ".vscode/.*"
    - ".editorconfig"

    # Infraestructura de Git y Hooks
    - ".git/.*"
    - ".github/ISSUE_TEMPLATE/.*"

# 2. Specific Detectors: If a detector is giving too many false positives,
# you can disable it here. (Use with caution.)

# exclude_detectors:
# - URI
# Disable if it alerts for harmless dev URLs


# 3. Verification Rules (Optional):
# You can force only findings that the engine can verify to be reported.
# verify: true
