name: "🚀 Petición de Nuevo Script"
description: "Propón una nueva automatización o mejora para el Baseline."
labels: ["enhancement"]
body:
  - type: input
    id: title
    attributes:
      label: "Nombre sugerido"
      placeholder: "Ej: deploy-to-s3.sh"
    validations:
      required: true
  - type: textarea
    id: goal
    attributes:
      label: "Objetivo"
      description: "¿Qué proceso quieres automatizar y cuánto tiempo esperas ahorrar?"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "Prioridad Estimada"
      options:
        - Baja (Mejora estética o docs)
        - Media (Ahorra tiempo semanal)
        - Alta (Crítico para el flujo de trabajo)
    validations:
      required: true
