name: Lint Bash

permissions:
  contents: read

on:
  push:
  pull_request_target:
    branches:
        - main

jobs:
  lint-shellcheck:
    name: Runner ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Detect changed shell scripts
        id: changed
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.sh

      - name: Skip ShellCheck if no shell scripts changed
        if: steps.changed.outputs.any_changed != 'true'
        run: echo "No shell scripts changed. ShellCheck skipped."

      - name: Run ShellCheck
        if: steps.changed.outputs.any_changed == 'true'
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          version: v0.11.0
          scandir: './'
        env:
          SHELLCHECK_OPTS: -e SC1091 # Ignora errores de "source" de archivos externos
