name: Linting de Scripts Bash

permissions:
  contents: read

on:
  push:                 # Feedback temprano al pushear
    branches:
        - 'feat/**'     # Feedback temprano en desarrollo
        - 'fix/**'      # Feedback temprano en correcciones
        - 'hotfix/**'   # Feedback temprano en hotfixes
  pull_request:         # Gatekeeper para el merge
    branches:
        - main          # Gatekeeper final para producción
        - dev           # Validación para integrar nuevas funcionalidades
        - 'release/**'  # Validación para ramas de estabilización

jobs:
  shellcheck:
    name: Runner ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Check for script changes
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            **/*.sh

      - name: ShellCheck Execution
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: ludeeus/action-shellcheck@master
        with:
          # Escanea todas las carpetas del repo en busca de .sh
          scandir: './'
        env:
          # Opcional: Ignorar algunos errores específicos si fuera necesario
          SHELLCHECK_OPTS: -e SC1091 # Ignora errores de "source" de archivos externos

      - name: Finalize Status
        # Corre SIEMPRE, haya scripts o no, para dar el "verde" al Ruleset
        if: always()
        run: |
          if [ "${{ steps.changed-files.outputs.any_changed }}" == "true" ]; then
            echo "Checks completed."
          else
            echo "No scripts to check, status: Success."
          fi
